GET http://localhost:3001/api/category
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsInVzZXJJZCI6IjVjMWNmMzlhYjVhYjlhMmRlMmE1NjA0YyIsImlhdCI6MTU0NTU0OTczNywiZXhwIjoxNTQ1NTUzMzM3fQ.yV_80ZY68wM028xKCyFMUrIrrwhp3OqxV7Ww7Lio0vo