PUT http://localhost:3003/api/blogs/5bd72daa10ccacb53ccbb7a
Content-Type: application/json

{
  "title": "How To Combine a NodeJS Back End with a ReactJS Front End App.",
  "author": "Ethan Jarrell",
  "url": "https://hackernoon.com/how-to-combine-a-nodejs-back-end-with-a-reactjs-front-end-app-ea9b24715032",
  "likes": 3155
}